import Link from "next/link";
import { getCurrentContext, money } from "@/lib/accounting";
import { receiveRendition, createRendition } from "../actions";
export default async function AgentPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const {supabase:rawSupabase,organization}=await getCurrentContext(); const supabase:any=rawSupabase; if(!organization)return null;
 const [a,r,c]=await Promise.all([supabase.from("agency_agents").select("*").eq("id",id).eq("organization_id",organization.id).single(),supabase.from("agency_renditions").select("id,rendition_date,period_start,period_end,amount_due,status,reference").eq("agent_id",id).eq("organization_id",organization.id).order("rendition_date",{ascending:false}),supabase.from("cash_accounts").select("id,name,currency_code").eq("organization_id",organization.id).eq("is_active",true).order("name")]);
 if(!a.data)return <div className="page"><p>No se encontró el operador.</p><Link href="/agencia">Volver</Link></div>;
 const rows=r.data??[], ids=rows.map(x=>x.id); const {data:p}=ids.length?await supabase.from("agency_rendition_payments").select("rendition_id,amount").in("rendition_id",ids):{data:[]}; const pm=new Map<string,number>();for(const x of p??[])pm.set(x.rendition_id,(pm.get(x.rendition_id)||0)+Number(x.amount));
 const due=rows.reduce((s,x)=>s+Number(x.amount_due),0),paid=(p??[]).reduce((s,x)=>s+Number(x.amount),0),pending=Math.max(due-paid,0);
 return <div className="page"><div className="agent-hero"><div><Link className="back-link" href="/agencia">← Agencia</Link><p className="eyebrow">{a.data.kind==="subagent"?"SUBAGENTE":"AMBULANTE"}</p><h1>{a.data.full_name}</h1><p className="muted">{a.data.code||"Sin código"} · {a.data.phone||"Sin teléfono"}{a.data.whatsapp?" · WhatsApp "+a.data.whatsapp:""}</p></div><div className="agent-hero-contact"><span>Estado</span><strong className="badge success">Activo</strong></div></div>
 <div className="stats-grid compact"><div className="stat-card"><span>Total a rendir</span><strong>{money(due,organization.currency_code)}</strong></div><div className="stat-card"><span>Total recibido</span><strong>{money(paid,organization.currency_code)}</strong></div><div className="stat-card stat-card-pending"><span>Pendiente</span><strong>{money(pending,organization.currency_code)}</strong></div></div>
 <section className="panel form-panel"><div className="panel-head"><div><h2>Nueva rendición</h2><p className="muted">Registrá cuánto debe entregar este operador.</p></div></div><form action={createRendition} className="agency-rendition-form"><input type="hidden" name="agent_id" value={id}/><label>Fecha<input name="rendition_date" type="date" required/></label><label>Desde<input name="period_start" type="date"/></label><label>Hasta<input name="period_end" type="date"/></label><label>Importe a rendir<input name="amount_due" type="number" min="0.01" step="0.01" required/></label><label>Referencia<input name="reference" placeholder="Opcional"/></label><button className="button primary">Crear rendición</button></form></section>
 <section className="panel table-panel"><div className="panel-head"><div><h2>Historial de rendiciones</h2><p className="muted">Cada entrega queda vinculada a una rendición.</p></div></div><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Período</th><th>Debe</th><th>Recibido</th><th>Pendiente</th><th>Estado</th><th></th></tr></thead><tbody>{rows.map(x=>{const pr=pm.get(x.id)||0,pend=Math.max(Number(x.amount_due)-pr,0);return <tr key={x.id}><td>{x.rendition_date}</td><td>{x.period_start||"—"} → {x.period_end||"—"}</td><td>{money(x.amount_due,organization.currency_code)}</td><td>{money(pr,organization.currency_code)}</td><td className="money-pending">{money(pend,organization.currency_code)}</td><td><span className={"badge "+(x.status==="closed"?"success":"")}>{x.status==="closed"?"Cerrada":"Abierta"}</span></td><td>{x.status!=="closed"&&<details><summary className="table-link">Recibir</summary><form action={receiveRendition} className="receive-form"><input type="hidden" name="rendition_id" value={x.id}/><input type="hidden" name="agent_id" value={id}/><input name="payment_date" type="date" required/><input name="amount" type="number" min="0.01" max={pend} step="0.01" placeholder={String(pend)} required/><select name="cash_account_id" required><option value="">Caja</option>{(c.data??[]).map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select><input name="reference" placeholder="Referencia"/><button className="button primary">Confirmar</button></form></details>}</td></tr>})}</tbody></table></div></section>
 <section className="panel"><div className="detail-grid"><div><span>DNI</span><strong>{a.data.dni||"—"}</strong></div><div><span>Domicilio</span><strong>{a.data.address||"—"}</strong></div><div><span>Observaciones</span><strong>{a.data.notes||"—"}</strong></div></div></section></div>;
}