-- Agency administrative layer: operators, renditions, daily closing and audit.
alter table public.agency_agents add column if not exists dni text, add column if not exists email text;
create table if not exists public.agency_daily_closings (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 closing_date date not null, expected_amount numeric not null default 0 check(expected_amount>=0), received_amount numeric not null default 0 check(received_amount>=0), pending_amount numeric not null default 0 check(pending_amount>=0), cash_balance numeric not null default 0,
 notes text,status text not null default 'open' check(status in ('open','closed')),closed_by uuid references auth.users(id),closed_at timestamptz,created_by uuid not null default auth.uid() references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,closing_date));
alter table public.agency_daily_closings enable row level security;
create policy agency_daily_closings_select on public.agency_daily_closings for select to authenticated using(private.is_org_member(organization_id,(select auth.uid())));
create policy agency_daily_closings_insert on public.agency_daily_closings for insert to authenticated with check(private.is_org_accounting(organization_id,(select auth.uid())));
create policy agency_daily_closings_update on public.agency_daily_closings for update to authenticated using(private.is_org_accounting(organization_id,(select auth.uid()))) with check(private.is_org_accounting(organization_id,(select auth.uid())));
create or replace function public.create_agency_agent(p_organization_id uuid,p_kind public.agency_agent_kind,p_full_name text,p_code text default null,p_dni text default null,p_phone text default null,p_whatsapp text default null,p_address text default null,p_notes text default null) returns uuid language plpgsql set search_path=public,pg_temp as $$declare v_id uuid;begin if not exists(select 1 from public.organization_members where organization_id=p_organization_id and user_id=auth.uid() and role in ('owner','admin')) then raise exception 'Sin permisos';end if;if trim(coalesce(p_full_name,''))='' then raise exception 'El nombre es obligatorio';end if;insert into public.agency_agents(organization_id,kind,full_name,code,dni,phone,whatsapp,address,notes,created_by) values(p_organization_id,p_kind,trim(p_full_name),nullif(trim(p_code),''),nullif(trim(p_dni),''),nullif(trim(p_phone),''),nullif(trim(p_whatsapp),''),nullif(trim(p_address),''),nullif(trim(p_notes),''),auth.uid()) returning id into v_id;insert into public.audit_log(organization_id,user_id,action,entity,entity_id,payload) values(p_organization_id,auth.uid(),'create','agency_agent',v_id,jsonb_build_object('kind',p_kind,'full_name',trim(p_full_name)));return v_id;end;$$;
revoke execute on function public.create_agency_agent(uuid,public.agency_agent_kind,text,text,text,text,text,text,text) from public,anon;grant execute on function public.create_agency_agent(uuid,public.agency_agent_kind,text,text,text,text,text,text,text) to authenticated;
create or replace function public.create_agency_rendition(p_organization_id uuid,p_agent_id uuid,p_rendition_date date,p_period_start date,p_period_end date,p_amount_due numeric,p_reference text default null,p_notes text default null) returns uuid language plpgsql set search_path=public,pg_temp as $$declare v_id uuid;begin if not exists(select 1 from public.organization_members where organization_id=p_organization_id and user_id=auth.uid() and role in ('owner','admin','accountant')) then raise exception 'Sin permisos';end if;if p_amount_due<=0 then raise exception 'El importe debe ser mayor que cero';end if;if not exists(select 1 from public.agency_agents where id=p_agent_id and organization_id=p_organization_id and is_active) then raise exception 'Operador inválido';end if;insert into public.agency_renditions(organization_id,agent_id,rendition_date,period_start,period_end,amount_due,reference,notes,created_by) values(p_organization_id,p_agent_id,p_rendition_date,p_period_start,p_period_end,p_amount_due,nullif(trim(p_reference),''),nullif(trim(p_notes),''),auth.uid()) returning id into v_id;insert into public.audit_log(organization_id,user_id,action,entity,entity_id,payload) values(p_organization_id,auth.uid(),'create','agency_rendition',v_id,jsonb_build_object('agent_id',p_agent_id,'amount_due',p_amount_due));return v_id;end;$$;
revoke execute on function public.create_agency_rendition(uuid,uuid,date,date,date,numeric,text,text) from public,anon;grant execute on function public.create_agency_rendition(uuid,uuid,date,date,date,numeric,text,text) to authenticated;
create or replace function public.close_agency_day(p_organization_id uuid,p_closing_date date,p_notes text default null) returns uuid language plpgsql set search_path=public,pg_temp as $$declare v_id uuid;v_expected numeric;v_received numeric;v_pending numeric;v_cash numeric;begin if not exists(select 1 from public.organization_members where organization_id=p_organization_id and user_id=auth.uid() and role in ('owner','admin','accountant')) then raise exception 'Sin permisos';end if;select coalesce(sum(amount_due),0) into v_expected from public.agency_renditions where organization_id=p_organization_id and rendition_date=p_closing_date and status<>'void';select coalesce(sum(p.amount),0) into v_received from public.agency_rendition_payments p join public.agency_renditions r on r.id=p.rendition_id where p.organization_id=p_organization_id and p.payment_date=p_closing_date;v_pending:=greatest(v_expected-v_received,0);select coalesce(sum(case when direction='incoming' then amount else -amount end),0) into v_cash from public.cash_movements where organization_id=p_organization_id and movement_date<=p_closing_date;insert into public.agency_daily_closings(organization_id,closing_date,expected_amount,received_amount,pending_amount,cash_balance,notes,status,closed_by,closed_at,created_by,updated_at) values(p_organization_id,p_closing_date,v_expected,v_received,v_pending,v_cash,p_notes,'closed',auth.uid(),now(),auth.uid(),now()) on conflict(organization_id,closing_date) do update set expected_amount=excluded.expected_amount,received_amount=excluded.received_amount,pending_amount=excluded.pending_amount,cash_balance=excluded.cash_balance,notes=excluded.notes,status='closed',closed_by=auth.uid(),closed_at=now(),updated_at=now() returning id into v_id;insert into public.audit_log(organization_id,user_id,action,entity,entity_id,payload) values(p_organization_id,auth.uid(),'close','agency_daily_closing',v_id,jsonb_build_object('date',p_closing_date,'expected',v_expected,'received',v_received,'pending',v_pending));return v_id;end;$$;
revoke execute on function public.close_agency_day(uuid,date,text) from public,anon;grant execute on function public.close_agency_day(uuid,date,text) to authenticated;